server:
  port: 9010
spring:
  mail:
    username: billoapplication@gmail.com
    password: qaglpssojzyxocrf
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    topic:
      name: longcovvid_notification_topic
    consumer:
      bootstrap-servers: broker:29092
      group-id: notification
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka
