server:
  port: 9010
spring:
  mail:
    username: myplanetdobremihai@gmail.com
    password: bvrvoxlipavhvyvj
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    topic:
      name: longcovvid_notification_topic
    consumer:
      bootstrap-servers: broker:9092
      group-id: notification
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

#Actuator Prometheus Endpoint
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
    shutdown:
      enabled: true
    info:
      env:
        enabled: true
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus, metrics, info, health, shutdown, beans
